/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;

public class AppTest {

    @Before
    public void setUp () {

    }

    @Test
    public void testGenerateRandomInt () {

    }

    @Test
    public void testReadBookQuote () {

    }
}
