/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {
    public String getGreeting() {
        return "Hello world. Here, have some quotes!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }

    public static String readBook (Book book) {
        String bookString = "";
        String currentLine = book.bookScanner.nextLine();

        while (book.bookScanner.nextLine() !=null) {
            bookString += currentLine;
            currentLine = book.bookScanner.nextLine();
        }
        return bookString;
    }
}
