/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

//import com.google.gson.Gson;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {

        Book book = new Book ("src/main/resources/recentquotes.json");

        findQuoteOnline(book);

    }

    public static void findQuoteOnline (Book book) {
        Gson gson = new Gson();
        try {
            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");

            try {
                HttpURLConnection connect = (HttpURLConnection) url.openConnection();
                BufferedReader apiReturn = new BufferedReader(new InputStreamReader(connect.getInputStream()));
                String quoteArray = apiReturn.readLine();
                String quote = quoteArray.substring(1, quoteArray.length() - 1);


                System.out.println(quote + " ~ Ron Swanson");
                Quote ronSays = new Quote (quote, "Ron Swanson");

                Reader bookReader = new FileReader(book.bookPath);
                Quote[] bookQuotes = gson.fromJson(bookReader, Quote[].class);
                Quote[] addedQuotes = Arrays.copyOf(bookQuotes, bookQuotes.length + 1);
                addedQuotes[bookQuotes.length - 1] = ronSays;

                FileWriter write = new FileWriter("src/main/resources/recentquotes.json");
                write.write(gson.toJson(addedQuotes));
                write.close();


            } catch (IOException e) {
                System.out.println("IDK where the internet went. But here's a quote we had saved.");
                String qu = readBookQuote(book);
                System.out.println(qu);

                e.printStackTrace();
            }
        } catch (MalformedURLException e) {
            System.out.println("Use a real URL next time. For now here's a local quote.");
            String qu = readBookQuote(book);
            System.out.println(qu);

            e.printStackTrace();
        }

    }

    public static String readBookQuote (Book book) {
        Gson gson = new Gson();
        try {
            Reader bookReader = new FileReader(book.bookPath);
            Quote[] bookQuotes = gson.fromJson(bookReader, Quote[].class);
            int quoteAt = generateRandomInt(bookQuotes.length);
            return gson.toJson(bookQuotes[quoteAt].toString());
            //do the random number thing here
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static int generateRandomInt (int max) {
        return (int) Math.floor(Math.random() * max);
    }
}
